/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

import com.constant.Constants;
import com.dao.DateDAO;
import com.model.Date;
import com.model.Faculty;
import com.service.ReservationService;
import com.utils.CommonUtil;
import com.utils.MessageUtil;
import com.utils.StringUtils;
import java.util.List;
import com.component.ui.CustomTable;
import com.dao.FacultyDAO;
import com.dao.ReservationDAO;
import com.dao.RoomDAO;
import com.dto.AllDate;
import com.dto.AllFaculty;
import com.dto.AllRoom;
import com.dto.ComboboxItem;
import com.dto.ReservationDTO;
import com.model.Room;
import com.service.DateService;
import com.service.FacultyService;
import com.service.RoomService;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

public class RoomScheduler extends javax.swing.JFrame {

    /**
     * Creates new form RoomScheduler
     */
    public RoomScheduler() {
        initComponents();
        initOther();
        showReservationList();
    }

    private void initOther() {
        CommonUtil.installNumberSoTextField(txtSeats);
        CommonUtil.installNumberSoTextField(txtAddRoomSeats);
        CommonUtil.setLocationCenter(this);
        CommonUtil.hideFirstColumn(this.tblRoom);
        CommonUtil.hideFirstColumn(this.tblWaiting);
        loadItemsCbxReservationFilterStatus();
    }

    private void loadItemsCbxReservationFilterStatus() {
        List<ComboboxItem> lstStatus = Constants.RESERVASION_STATUS.getLstStatus();
        lstStatus.stream().forEach(status -> this.cbxReservationFilterStatus.addItem(status));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAddRoom = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtAddRoomName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnAddRoom = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtAddRoomSeats = new javax.swing.JTextField();
        btnCancelNewRoom = new javax.swing.JButton();
        pnlAddFaculty = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAddFacultyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAddFaculty = new javax.swing.JButton();
        btnCancelNewFaculty = new javax.swing.JButton();
        pnlReserveRoom = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnReserve = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSeats = new javax.swing.JTextField();
        cbxDateReverse = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cbxFacultyReverse = new javax.swing.JComboBox<>();
        btnCancelNewReservation = new javax.swing.JButton();
        pnlReservationList = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cbxReservationFilterFaculty = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cbxReservationFilterDate = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cbxReservationFilterStatus = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cbxReservationFilterRoom = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblWaiting = new com.component.ui.ReservationTable();
        jPanel6 = new javax.swing.JPanel();
        btnCancelReservation = new javax.swing.JButton();
        btnAddReservation = new javax.swing.JButton();
        pnlRoomList = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRoom = new com.component.ui.RoomTable();
        jPanel4 = new javax.swing.JPanel();
        btnAddRoomInList = new javax.swing.JButton();
        btnDeleteRoom = new javax.swing.JButton();
        pnlAddDate = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnAddDate = new javax.swing.JButton();
        dateNewDate = new com.toedter.calendar.JDateChooser();
        btnCancelNewDate = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenu();
        menuItemAddFaculty = new javax.swing.JMenuItem();
        menuItemAddRoom = new javax.swing.JMenuItem();
        menuItemAddReservation = new javax.swing.JMenuItem();
        menuItemAddDate = new javax.swing.JMenuItem();
        menuList = new javax.swing.JMenu();
        menuItemWaitingList = new javax.swing.JMenuItem();
        menuItemRoomList = new javax.swing.JMenuItem();
        menuItemQuit = new javax.swing.JMenuItem();

        pnlAddRoom.setMaximumSize(new java.awt.Dimension(1018, 747));
        pnlAddRoom.setMinimumSize(new java.awt.Dimension(1018, 747));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Room Name: ");

        txtAddRoomName.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Add Room");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAddRoom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addNew24.png")));
        btnAddRoom.setText(" Add");
        btnAddRoom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Seats:");

        txtAddRoomSeats.setText("30");

        btnCancelNewRoom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelNewRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit24.png")));
        btnCancelNewRoom.setText(" Cancel");
        btnCancelNewRoom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelNewRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNewRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddRoomLayout = new javax.swing.GroupLayout(pnlAddRoom);
        pnlAddRoom.setLayout(pnlAddRoomLayout);
        pnlAddRoomLayout.setHorizontalGroup(
            pnlAddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlAddRoomLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(pnlAddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAddRoomLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(txtAddRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddRoomLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(pnlAddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddRoomSeats)
                            .addGroup(pnlAddRoomLayout.createSequentialGroup()
                                .addComponent(btnAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelNewRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        pnlAddRoomLayout.setVerticalGroup(
            pnlAddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddRoomLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(pnlAddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnlAddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtAddRoomSeats))
                .addGap(60, 60, 60)
                .addGroup(pnlAddRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelNewRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(382, Short.MAX_VALUE))
        );

        pnlAddFaculty.setMaximumSize(new java.awt.Dimension(1018, 747));
        pnlAddFaculty.setMinimumSize(new java.awt.Dimension(1018, 747));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Faculty Name: ");

        txtAddFacultyName.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Faculty");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAddFaculty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddFaculty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addNew24.png")));
        btnAddFaculty.setText(" Add");
        btnAddFaculty.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFacultyActionPerformed(evt);
            }
        });

        btnCancelNewFaculty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelNewFaculty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit24.png")));
        btnCancelNewFaculty.setText(" Cancel");
        btnCancelNewFaculty.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelNewFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNewFacultyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddFacultyLayout = new javax.swing.GroupLayout(pnlAddFaculty);
        pnlAddFaculty.setLayout(pnlAddFacultyLayout);
        pnlAddFacultyLayout.setHorizontalGroup(
            pnlAddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlAddFacultyLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(pnlAddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddFacultyLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(txtAddFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddFacultyLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnAddFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnCancelNewFaculty)))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        pnlAddFacultyLayout.setVerticalGroup(
            pnlAddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddFacultyLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(pnlAddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnlAddFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelNewFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(477, Short.MAX_VALUE))
        );

        pnlReserveRoom.setMaximumSize(new java.awt.Dimension(1018, 747));
        pnlReserveRoom.setMinimumSize(new java.awt.Dimension(1018, 747));
        pnlReserveRoom.setPreferredSize(new java.awt.Dimension(1018, 747));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reserve Room");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnReserve.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReserve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addNew24.png")));
        btnReserve.setText(" Reserve");
        btnReserve.setToolTipText("");
        btnReserve.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Date:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Seats Number: ");

        txtSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatsActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Faculty:");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnCancelNewReservation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelNewReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit24.png")));
        btnCancelNewReservation.setText(" Cancel");
        btnCancelNewReservation.setToolTipText("");
        btnCancelNewReservation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelNewReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNewReservationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlReserveRoomLayout = new javax.swing.GroupLayout(pnlReserveRoom);
        pnlReserveRoom.setLayout(pnlReserveRoomLayout);
        pnlReserveRoomLayout.setHorizontalGroup(
            pnlReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE)
            .addGroup(pnlReserveRoomLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addGroup(pnlReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReserveRoomLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(cbxFacultyReverse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlReserveRoomLayout.createSequentialGroup()
                        .addGroup(pnlReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(pnlReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlReserveRoomLayout.createSequentialGroup()
                                .addComponent(btnReserve)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelNewReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSeats)
                            .addComponent(cbxDateReverse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(369, 369, 369))
        );
        pnlReserveRoomLayout.setVerticalGroup(
            pnlReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReserveRoomLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(pnlReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxFacultyReverse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(pnlReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxDateReverse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(pnlReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(pnlReserveRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelNewReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(308, Short.MAX_VALUE))
        );

        pnlReservationList.setMaximumSize(new java.awt.Dimension(1018, 747));
        pnlReservationList.setMinimumSize(new java.awt.Dimension(1018, 747));
        pnlReservationList.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Reservation List");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setMaximumSize(new java.awt.Dimension(160, 50));
        jLabel9.setMinimumSize(new java.awt.Dimension(160, 50));
        jLabel9.setPreferredSize(new java.awt.Dimension(160, 50));
        pnlReservationList.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        jPanel2.setMaximumSize(new java.awt.Dimension(1018, 747));
        jPanel2.setMinimumSize(new java.awt.Dimension(1018, 747));
        jPanel2.setPreferredSize(new java.awt.Dimension(1018, 747));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Faculty: ");

        cbxReservationFilterFaculty.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxReservationFilterFacultyItemStateChanged(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Date: ");

        cbxReservationFilterDate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxReservationFilterDateItemStateChanged(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Status:");

        cbxReservationFilterStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxReservationFilterStatusItemStateChanged(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Room:");

        cbxReservationFilterRoom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxReservationFilterRoomItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxReservationFilterFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxReservationFilterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxReservationFilterRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxReservationFilterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxReservationFilterRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxReservationFilterStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxReservationFilterFaculty, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxReservationFilterDate, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        tblWaiting.setModel(new com.component.model.ReservationTableModel());
        jScrollPane2.setViewportView(tblWaiting);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        btnCancelReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete24.png")));
        btnCancelReservation.setText(" Cancel Reservation");
        btnCancelReservation.setToolTipText("");
        btnCancelReservation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelReservationActionPerformed(evt);
            }
        });

        btnAddReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addNew24.png")));
        btnAddReservation.setText(" New Reservation");
        btnAddReservation.setToolTipText("");
        btnAddReservation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddReservationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(592, Short.MAX_VALUE)
                .addComponent(btnAddReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnCancelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        pnlReservationList.add(jPanel2, java.awt.BorderLayout.CENTER);

        pnlRoomList.setMaximumSize(new java.awt.Dimension(1018, 747));
        pnlRoomList.setMinimumSize(new java.awt.Dimension(1018, 747));
        pnlRoomList.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Room List");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setMaximumSize(new java.awt.Dimension(160, 50));
        jLabel12.setMinimumSize(new java.awt.Dimension(160, 50));
        jLabel12.setPreferredSize(new java.awt.Dimension(160, 50));
        pnlRoomList.add(jLabel12, java.awt.BorderLayout.PAGE_START);

        jPanel3.setMaximumSize(new java.awt.Dimension(1018, 747));
        jPanel3.setMinimumSize(new java.awt.Dimension(1018, 747));
        jPanel3.setPreferredSize(new java.awt.Dimension(1018, 747));
        jPanel3.setLayout(new java.awt.BorderLayout());

        tblRoom.setModel(new com.component.model.RoomTableModel());
        jScrollPane3.setViewportView(tblRoom);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        btnAddRoomInList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addNew24.png")));
        btnAddRoomInList.setText(" Add Room");
        btnAddRoomInList.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddRoomInList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomInListActionPerformed(evt);
            }
        });

        btnDeleteRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete24.png")));
        btnDeleteRoom.setText(" Delete Room");
        btnDeleteRoom.setToolTipText("");
        btnDeleteRoom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDeleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(700, Short.MAX_VALUE)
                .addComponent(btnAddRoomInList, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnDeleteRoom)
                .addGap(38, 38, 38))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddRoomInList, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        pnlRoomList.add(jPanel3, java.awt.BorderLayout.CENTER);

        pnlAddDate.setMaximumSize(new java.awt.Dimension(1018, 747));
        pnlAddDate.setMinimumSize(new java.awt.Dimension(1018, 747));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Select Date:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Add Date");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAddDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addNew24.png")));
        btnAddDate.setText(" Add");
        btnAddDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDateActionPerformed(evt);
            }
        });

        btnCancelNewDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelNewDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit24.png")));
        btnCancelNewDate.setText(" Cancel");
        btnCancelNewDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelNewDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNewDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddDateLayout = new javax.swing.GroupLayout(pnlAddDate);
        pnlAddDate.setLayout(pnlAddDateLayout);
        pnlAddDateLayout.setHorizontalGroup(
            pnlAddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlAddDateLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(pnlAddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAddDateLayout.createSequentialGroup()
                        .addComponent(btnAddDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnCancelNewDate))
                    .addComponent(dateNewDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        pnlAddDateLayout.setVerticalGroup(
            pnlAddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddDateLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(pnlAddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(dateNewDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(pnlAddDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelNewDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(487, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        menu.setText("Menu");
        menu.setToolTipText("");

        menuNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addNew16.png")));
        menuNew.setText("New");

        menuItemAddFaculty.setText("Faculty");
        menuItemAddFaculty.setToolTipText("");
        menuItemAddFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddFacultyActionPerformed(evt);
            }
        });
        menuNew.add(menuItemAddFaculty);

        menuItemAddRoom.setText("Room");
        menuItemAddRoom.setToolTipText("");
        menuItemAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddRoomActionPerformed(evt);
            }
        });
        menuNew.add(menuItemAddRoom);

        menuItemAddReservation.setText("Reservation");
        menuItemAddReservation.setToolTipText("");
        menuItemAddReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddReservationActionPerformed(evt);
            }
        });
        menuNew.add(menuItemAddReservation);

        menuItemAddDate.setText("Date");
        menuItemAddDate.setToolTipText("");
        menuItemAddDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddDateActionPerformed(evt);
            }
        });
        menuNew.add(menuItemAddDate);

        menu.add(menuNew);

        menuList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list16.png")));
        menuList.setText("List");

        menuItemWaitingList.setText("Reservation List");
        menuItemWaitingList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemWaitingListActionPerformed(evt);
            }
        });
        menuList.add(menuItemWaitingList);

        menuItemRoomList.setText("Room List");
        menuItemRoomList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRoomListActionPerformed(evt);
            }
        });
        menuList.add(menuItemRoomList);

        menu.add(menuList);

        menuItemQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit16.png")));
        menuItemQuit.setText("Quit");
        menuItemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemQuitActionPerformed(evt);
            }
        });
        menu.add(menuItemQuit);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAddFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddFacultyActionPerformed
        CommonUtil.showItem(this.pnlMain, this.pnlAddFaculty);
    }//GEN-LAST:event_menuItemAddFacultyActionPerformed

    private void menuItemAddReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddReservationActionPerformed
        showPanelNewReservation();
    }//GEN-LAST:event_menuItemAddReservationActionPerformed

    public void showPanelNewReservation() {
        CommonUtil.showItem(this.pnlMain, this.pnlReserveRoom);
        this.txtSeats.setText("30");

        this.cbxFacultyReverse.removeAllItems();
        List<Faculty> lstFaculty = FacultyDAO.getAll();
        lstFaculty.stream().forEach(faculty -> this.cbxFacultyReverse.addItem(faculty));

        this.cbxDateReverse.removeAllItems();
        List<Date> lstDate = DateDAO.getAll();
        lstDate.stream().forEach(date -> this.cbxDateReverse.addItem(date));
    }

    private void menuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemQuitActionPerformed

    private void btnAddFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFacultyActionPerformed
        String facultyName = txtAddFacultyName.getText();
        if (StringUtils.isEmpty(facultyName)) {
            MessageUtil.showWarning(Constants.MESSAGE.FILL_ALL_FIELDS);
            return;
        }
        FacultyService.add(facultyName);
    }//GEN-LAST:event_btnAddFacultyActionPerformed

    private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed
        Date date = (Date) this.cbxDateReverse.getSelectedItem();
        Faculty faculty = (Faculty) this.cbxFacultyReverse.getSelectedItem();
        String seats = this.txtSeats.getText();
        if (date == null || faculty == null || !StringUtils.isInteger(seats)) {
            MessageUtil.showWarning(Constants.MESSAGE.FILL_ALL_FIELDS);
            return;
        }
        int existedId = ReservationDAO.checkReservationExists(date.getId(), faculty.getId());
        if (existedId > 0) {
            Object[] options = {"Yes", "No"};
            int btnClicked = JOptionPane.showOptionDialog(this, String.format(Constants.MESSAGE.CONFIRM_UPDATE_RESERVATION, faculty.getName(), CommonUtil.getDateFormat(date.getDate())), "Confirm update",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            if (btnClicked == JOptionPane.YES_OPTION) {
                ReservationService.updateReservation(date, Integer.valueOf(seats), existedId, faculty);
            }
        } else {
            ReservationService.addReservation(date, Integer.valueOf(seats), faculty);
        }
        showReservationList();
    }//GEN-LAST:event_btnReserveActionPerformed

    private void txtSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatsActionPerformed

    private void menuItemWaitingListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemWaitingListActionPerformed
        showReservationList();
    }//GEN-LAST:event_menuItemWaitingListActionPerformed

    private void menuItemAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddRoomActionPerformed
        CommonUtil.showItem(this.pnlMain, this.pnlAddRoom);
    }//GEN-LAST:event_menuItemAddRoomActionPerformed

    private void menuItemRoomListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRoomListActionPerformed
        showRoomList();
    }//GEN-LAST:event_menuItemRoomListActionPerformed

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        String roomName = this.txtAddRoomName.getText();
        String seats = this.txtAddRoomSeats.getText();
        if (StringUtils.isEmpty(roomName) || !StringUtils.isInteger(seats)) {
            MessageUtil.showWarning(Constants.MESSAGE.FILL_ALL_FIELDS);
            return;
        }
        int seatsNumber = Integer.valueOf(seats);
        int newId = RoomService.add(roomName, seatsNumber);
        if (newId > -1) {
            showRoomList();
        }
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void btnAddRoomInListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomInListActionPerformed
        CommonUtil.showItem(this.pnlMain, this.pnlAddRoom);
    }//GEN-LAST:event_btnAddRoomInListActionPerformed

    private void btnDeleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRoomActionPerformed
        int selectedRow = this.tblRoom.getSelectedRow();
        if (selectedRow > -1) {
            int roomId = (int) this.tblRoom.getModel().getValueAt(selectedRow, 0);
            String name = (String) this.tblRoom.getModel().getValueAt(selectedRow, 1);
            RoomService.delete(roomId, name);
        }
        showRoomList();
    }//GEN-LAST:event_btnDeleteRoomActionPerformed

    private void btnCancelReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelReservationActionPerformed
        int selectedRow = this.tblWaiting.getSelectedRow();
        if (selectedRow > -1) {
            int reservationId = (int) this.tblWaiting.getModel().getValueAt(selectedRow, 0);
            ReservationService.deleteReservation(reservationId);
            showReservationList();
        }
    }//GEN-LAST:event_btnCancelReservationActionPerformed

    private void cbxReservationFilterFacultyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxReservationFilterFacultyItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            getReservations();
        }
    }//GEN-LAST:event_cbxReservationFilterFacultyItemStateChanged

    private void menuItemAddDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddDateActionPerformed
        CommonUtil.showItem(pnlMain, pnlAddDate);
    }//GEN-LAST:event_menuItemAddDateActionPerformed

    private void btnAddDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDateActionPerformed
        java.util.Date selectedDate = this.dateNewDate.getDate();
//        java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
        java.util.Date current = new java.util.Date();
        if (selectedDate == null) {
            MessageUtil.showWarning("Please select a day!!");
            return;
        }

        if (CommonUtil.compareDateOnly(selectedDate, current) < 0) {
            MessageUtil.showWarning("Invalid date. Date must be equal to or greater than the current date\nPlease select another day!!");
            return;
        }

        System.out.println("selectedDate:" + selectedDate);
        DateService.add(new java.sql.Date(selectedDate.getTime()));
    }//GEN-LAST:event_btnAddDateActionPerformed

    private void cbxReservationFilterDateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxReservationFilterDateItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            getReservations();
        }
    }//GEN-LAST:event_cbxReservationFilterDateItemStateChanged

    private void cbxReservationFilterStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxReservationFilterStatusItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            getReservations();
        }
    }//GEN-LAST:event_cbxReservationFilterStatusItemStateChanged

    private void btnAddReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddReservationActionPerformed
        showPanelNewReservation();
    }//GEN-LAST:event_btnAddReservationActionPerformed

    private void btnCancelNewRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNewRoomActionPerformed
        showRoomList();
    }//GEN-LAST:event_btnCancelNewRoomActionPerformed

    private void btnCancelNewReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNewReservationActionPerformed
        showReservationList();
    }//GEN-LAST:event_btnCancelNewReservationActionPerformed

    private void btnCancelNewFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNewFacultyActionPerformed
        showReservationList();
    }//GEN-LAST:event_btnCancelNewFacultyActionPerformed

    private void btnCancelNewDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNewDateActionPerformed
        showReservationList();
    }//GEN-LAST:event_btnCancelNewDateActionPerformed

    private void cbxReservationFilterRoomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxReservationFilterRoomItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            getReservations();
        }
    }//GEN-LAST:event_cbxReservationFilterRoomItemStateChanged

    public void getReservations() {
        Faculty faculty = (Faculty) this.cbxReservationFilterFaculty.getSelectedItem();
        Date date = (Date) this.cbxReservationFilterDate.getSelectedItem();
        Room room = (Room) this.cbxReservationFilterRoom.getSelectedItem();
        ComboboxItem status = (ComboboxItem) this.cbxReservationFilterStatus.getSelectedItem();
        System.out.println("Searching reservations faculty:" + faculty + "/date:" + date + "/status:" + status + "/room:" + room);
        if (faculty != null && date != null && room != null && status != null) {
            List<ReservationDTO> reservations = ReservationDAO.search(faculty.getId(), date.getId(), status.getValue(), room.getId());
            ((CustomTable) this.tblWaiting).updateData(reservations);
        }
    }

    private void showReservationList() {
        this.cbxReservationFilterFaculty.removeAllItems();
        this.cbxReservationFilterFaculty.addItem(AllFaculty.getInstance());
        List<Faculty> lstFaculty = FacultyDAO.getAll();
        lstFaculty.stream().forEach(faculty -> this.cbxReservationFilterFaculty.addItem(faculty));

        this.cbxReservationFilterDate.removeAllItems();
        this.cbxReservationFilterDate.addItem(AllDate.getInstance());
        List<Date> lstDate = DateDAO.getAll();
        lstDate.stream().forEach(date -> this.cbxReservationFilterDate.addItem(date));

        this.cbxReservationFilterRoom.removeAllItems();
        this.cbxReservationFilterRoom.addItem(AllRoom.getInstance());
        List<Room> lstRoom = RoomDAO.getAll();
        lstRoom.stream().forEach(room -> this.cbxReservationFilterRoom.addItem(room));

        CommonUtil.showItem(this.pnlMain, this.pnlReservationList);
        getReservations();
    }

    private void showRoomList() {
        CommonUtil.showItem(this.pnlMain, this.pnlRoomList);
        List<Room> rooms = RoomDAO.getAll();
        ((CustomTable) this.tblRoom).updateData(rooms);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomScheduler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomScheduler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDate;
    private javax.swing.JButton btnAddFaculty;
    private javax.swing.JButton btnAddReservation;
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnAddRoomInList;
    private javax.swing.JButton btnCancelNewDate;
    private javax.swing.JButton btnCancelNewFaculty;
    private javax.swing.JButton btnCancelNewReservation;
    private javax.swing.JButton btnCancelNewRoom;
    private javax.swing.JButton btnCancelReservation;
    private javax.swing.JButton btnDeleteRoom;
    private javax.swing.JButton btnReserve;
    private javax.swing.JComboBox<com.model.Date> cbxDateReverse;
    private javax.swing.JComboBox<com.model.Faculty> cbxFacultyReverse;
    private javax.swing.JComboBox<com.model.Date> cbxReservationFilterDate;
    private javax.swing.JComboBox<com.model.Faculty> cbxReservationFilterFaculty;
    private javax.swing.JComboBox<com.model.Room> cbxReservationFilterRoom;
    private javax.swing.JComboBox<com.dto.ComboboxItem> cbxReservationFilterStatus;
    private com.toedter.calendar.JDateChooser dateNewDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem menuItemAddDate;
    private javax.swing.JMenuItem menuItemAddFaculty;
    private javax.swing.JMenuItem menuItemAddReservation;
    private javax.swing.JMenuItem menuItemAddRoom;
    private javax.swing.JMenuItem menuItemQuit;
    private javax.swing.JMenuItem menuItemRoomList;
    private javax.swing.JMenuItem menuItemWaitingList;
    private javax.swing.JMenu menuList;
    private javax.swing.JMenu menuNew;
    private javax.swing.JPanel pnlAddDate;
    private javax.swing.JPanel pnlAddFaculty;
    private javax.swing.JPanel pnlAddRoom;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlReservationList;
    private javax.swing.JPanel pnlReserveRoom;
    private javax.swing.JPanel pnlRoomList;
    private javax.swing.JTable tblRoom;
    private javax.swing.JTable tblWaiting;
    private javax.swing.JTextField txtAddFacultyName;
    private javax.swing.JTextField txtAddRoomName;
    private javax.swing.JTextField txtAddRoomSeats;
    private javax.swing.JTextField txtSeats;
    // End of variables declaration//GEN-END:variables
}
